services:
  - type: web
    name: kick-bot-listener
    env: docker
    plan: free
    region: frankfurt
    # ЭТА СТРОКА ГОВОРИТ RENDER, КАК ПРОВЕРЯТЬ, ЖИВ ЛИ БОТ
    healthCheckPath: /health 
    envVars:
      - fromGroup: kick-bot-secrets
